
namespace ROFLPlay.DiffuseX {
	
	public enum ResponseCode {
		ABOUTUS_CONFIRM = 100,
		ABOUTUS_CANCEL = 101,
		LIKE_CONFIRM = 200,
		LIKE_CANCEL = 201,
		RATE_CONFIRM = 300,
		RATE_CANCEL = 301,
		ADVISE_CONFIRM = 400,
		ADVISE_CANCEL = 401,
		INTERSTITIAL_CONFIRM = 500,
		INTERSTITIAL_CANCEL = 501
	};

}
